#! /usr/bin/python
import os, sys

HOME=os.getenv("HOME")

commandMap = {
  "nexus" : "sudo mtpfs -o allow_other /nexus",
  "nexus4" : "sudo mtpfs -o allow_other /media/nexus4",
  "website-skt": HOME + "/appengine-java/bin/appcfg.sh update ~/sanskritnlpjava/war",
  "website": HOME + "/google_appengine/appcfg.py update ~/google_appengine/appEngine;" + HOME + "/appengine-java/bin/appcfg.sh update ~/sanskritnlpjava/war",
#grep -Ri --include=*.tex "some_string" some_directory
  "grep": "grep -Ri",
  "find": "find . -name -R -print ",
}
command = commandMap[sys.argv[1]]
command = command + " " + " ".join(sys.argv[2:])
print command
os.system(command)

